Cargo.toml
src/bn256/fq2.rs

For EVM verifier to get bytes of G2 generator.

Implement `ff::PrimeField::to_repr` for `bn256::Fq2`

---

README.md
src/bn256/fq12.rs
src/bn256/mod.rs

It would be helpful for these structs to be public for use in other applications involving, e.g., pairing. (For example we use it to generate witnesses in some SNARKs.) If there is no security concern, then please expose these structs as public. 
I also fixed a few comments where the Frobenius coefficient comment was copied from BLS12-381 and the numbers are different for BN254. (The implementation is fine.)

Make `Fq2`, `Fq6`, `Fq12` public

---

Cargo.toml
benches/less_than.rs
src/arithmetic.rs
src/bn256/assembly.rs
src/bn256/curve.rs
src/bn256/engine.rs
src/bn256/fq.rs
src/bn256/fq12.rs
src/bn256/fq2.rs
src/bn256/fq6.rs
src/bn256/fr.rs
src/bn256/mod.rs
src/derive/curve.rs
src/derive/field.rs
src/lib.rs
src/secp256k1/curve.rs
src/secp256k1/fp.rs
src/secp256k1/fq.rs
src/serde.rs
src/tests/curve.rs
src/tests/field.rs

Montgomery reduction dramatically slows down serialization speed for large halo2 proving keys.
Currently curves are serialized in compressed affine form. Deserializing involves a square root which is very expensive. For production purposes it is generally preferred to trade off more storage space for speed savings.

Add trait to serialize field and curve objects directly into raw bytes without Montgomery reduction

---

Cargo.toml

In the current setting, if a downstream lib uses `start_timer!` it automatically prints the timers because this `halo2curves` lib has this feature enabled.
Sometimes those timer info can be quite long and would love to have an option to switch it on/off.

FEAT: allow the downstream to decide whether to enable `print-trace`

---

Cargo.toml
src/arithmetic.rs
src/bn256/curve.rs
src/bn256/engine.rs
src/bn256/fq.rs
src/bn256/fq12.rs
src/bn256/fq2.rs
src/bn256/fq6.rs
src/bn256/fr.rs
src/derive/curve.rs
src/derive/field.rs
src/derive/mod.rs
src/lib.rs
src/pairing.rs
src/secp256k1/curve.rs
src/secp256k1/fp.rs
src/secp256k1/fq.rs
src/tests/curve.rs
src/tests/field.rs

Since `ff` and `group` 0.13.0 versions and 0.5.0 release for `pasta_curves`, `FieldExt` and `Group` traits have been merged into `Field` and `PrimeField`.
Also, some new traits have appeared such as `WithSmallOrderMultiplicative` and `FromUniformBytes`.
This PR reworks the implementation of all the aforementioned traits to be able to update the codebase to the latest `ff`, `group` and `pasta_curves` dependency versions.
Also, note that aside from the trait-related work, some constants have been computed and included in the lib. And others have been left to `0` as they'll never be used.
In any case, I've left with `TODO` marked all the things I'd like advice for.
Resolves: #18

Port crate to pasta 0.5.0 and ff & group 0.13.0

---

benches/less_than.rs
src/derive/curve.rs

f33059b1be8fee408e156c155dd009bfbff32969 (this PR)
Group operations/double/                                                                            
time:   [226.02 µs 227.16 µs 228.61 µs]
Group operations/add/   time:   [322.37 µs 322.60 µs 322.85 µs]                                  
67cc0a2a6bf4fd7f986669504202ca29261bf644 (before this PR)
Group operations/double/                                                                            
time:   [235.54 µs 235.64 µs 235.75 µs]
Group operations/add/   time:   [323.36 µs 323.60 µs 323.86 µs]  
093c4dc12bee6ca54a0254534ba2d6497f3b3d67 (using old formula)
Group operations/double/                                                                            
time:   [198.25 µs 198.31 µs 198.38 µs]
Group operations/add/   time:   [387.00 µs …

optimize "mul by 3b"

---

Cargo.toml

set `reexport` feature as default, see discussion: https://github.com/privacy-scaling-explorations/halo2curves/pull/30#issuecomment-1463525486

set reexport as default

---

src/bn256/curve.rs
src/bn256/fr.rs
src/grumpkin/curve.rs
src/grumpkin/mod.rs
src/lib.rs

Parameters are taken from https://github.com/AztecProtocol/barretenberg/blob/master/cpp/src/barretenberg/ecc/curves/grumpkin/grumpkin.hpp (same as https://github.com/jules/grumpkin/blob/main/src/curve.rs).
Based on #40
Resolves https://github.com/privacy-scaling-explorations/halo2curves/issues/35

Add `grumpkin` curve module

---

Cargo.toml

Allows us to use the most recent changes in Halo2 :)
I'm not sure how the tag is created, does that happen automatically?

Bump version to 0.3.3

---

src/bn256/curve.rs
src/bn256/fq.rs
src/derive/curve.rs
src/grumpkin/curve.rs
src/lib.rs
src/secp256r1/curve.rs
src/secp256r1/fp.rs
src/secp256r1/fq.rs
src/secp256r1/mod.rs

Adds new directory `secp256r1` that adds the [NIST P-256](https://neuromancer.sk/std/nist/P-256) curve and its relevant arithmetic operations.
To do this, also modified the macros in `src/derive/curve.rs` to account for curves where `a ≠ 0`. Because `bn256` and `secp256k1` both have `a = 0`, the elliptic curve operations (`add()`, `double()`, `is_on_curve()`, etc) used calculations that made this assumption. Since `secp256r1` has `a = 0xfff...fffc`, these operations needed to be refactored.
Tests mirror those of the `secp256k1` curve. Additionally added a test that checks the ZETA value of the curve.
Thank you to @CPerezz for helping me debug the tests and @enricobottazzi for investigating this library!

Add `secp256r1` curve

---

.github/workflows/ci.yml
Cargo.toml
src/bn256/curve.rs
src/bn256/engine.rs
src/bn256/fr.rs
src/derive/curve.rs
src/grumpkin/curve.rs
src/hash_to_curve.rs
src/lib.rs
src/secp256k1/curve.rs
src/secp256r1/curve.rs
src/secp256r1/fp.rs
src/secp256r1/fq.rs
src/tests/curve.rs
src/tests/field.rs
src/tests/mod.rs

This PR takes the `hash_to_field` from `pasta_curves` and implements the rest `CurveExt::hash_to_curve` for these curves:
- `bn256::G1` and `grumpkin::G1`
With [Shallue-van de Woestijne method]. Originally I was exploring implementation of [Simplified SWU for AB == 0] for them, but after playing with the sage script to find their isogeny it turns out the degree is so high (59) which might be even slower than the SVDW method (I saw in gnark they are also using SVDW method for BN256).
Although the spec doens't prepare test vectors for these 2 curves, I found in `gnark` they have the output of the same input from the spec with the same method for `bn254` [here](https://github.com/ConsenSys/gnark-crypto/blob/441dc0ffe639294b8d09e394f24ba7575577229c/ecc/bn254/hash_vectors_test.go#L29), so …

Implement `CurveExt::hash_to_curve` for `{bn256::G1,grumpkin::G1}`

---

src/derive/curve.rs
src/tests/curve.rs

This is a fixed in #44 by @chaosma but it's overwritten by #47 which forgets to pick it.
The check was passing because we are testing in release mode which doesn't have `debug-assertions` enabled, while `Choice::from(u8)` only uses `debug_assert` to check input is a bool.

Mask `ysign` as `bool`

---

Makefile

Resolves: #61 (or at least prevents it to happen again)

fix: Alert if publisher doesn't have cargo-release installed

---

Cargo.toml
benches/group.rs
benches/less_than.rs

The purpose of this PR is to add benchmarks for all basic group operations.
In particular we want to evaluate the impact on performance that the changes introduced by #19 have had.

Add basic group operation benchmarks

---

Cargo.toml

This should release Secp cycle as well as some performance improvements.
This also unblocks https://github.com/microsoft/Nova/pull/199

chore: Bump to 0.4

---

benches/group.rs
benches/hash_to_curve.rs
src/bn256/fq2.rs
src/derive/curve.rs
src/legendre.rs

This PR aims to mitigate the performance drop of curves with `a = 0` since #34. It also fixes some clippy warnings.
The benchmark of `group.rs` has the similar output (± 2%) as commit 21def8d900f088b325b61d6d8fe2777975960d28 that is right before #34.
Resolves #71.

Bring back curve algorithms for `a = 0`

---

Cargo.toml
src/bn256/fq.rs
src/bn256/fr.rs
src/derive/field.rs
src/secp256k1/fp.rs
src/secp256k1/fq.rs
src/secp256r1/fp.rs
src/secp256r1/fq.rs
src/tests/field.rs

256-bit field serialization is currently 4x u64, ie. the native format which isn't common 
This implements the standard byte-serialization for those fields (corresponding to the `PrimeField::{to,from}_repr`), and an hex-encoded variant of those bytes for (de)serializers that are human-readable (e.g. json) and hence typically not raw byte-friendly.
Hex is a straightforward, common and very simple choice for string formats that's [harder to mess up than Base64](https://eprint.iacr.org/2022/361).
- Added a new macro `serialize_deserialize_32_byte_primefield!` for custom serialization and deserialization of 32-byte prime field in different struct (Fq, Fp, Fr) across the secp256r, bn256, and secp256k1 modules.
- Implemented the new macro for serialization and deserialization in various …

fix: Improve serialization for prime fields

---

Cargo.toml
src/lib.rs

Since https://github.com/privacy-scaling-explorations/halo2curves/pull/69 the mod `pairing` is no longer accessible by `halo2curves::pairing`, this PR aims to fix this to make downstream easier to maintain the dependency.

Re-export also mod `pairing` and remove flag `reexport` to alwasy re-export

---

Cargo.toml

Following #93, field benches should not require reexport or they aren't run.

fix regression in #93 reexport field benches aren't run

---

src/derive/curve.rs

It seems this special case optimization was not being triggered because the `CURVE_ID` didn't match.

[fix/optimization] `mul_by_3b` special case should be `CURVE_ID == "bn256_g1"`

---

src/bn256/fq12.rs
src/bn256/fq2.rs
src/bn256/fq6.rs

Fixes #91 and #90.
This PR removes some unused functions and corrects some comments regarding its constants.

Fix nits in `bn256`.

---

src/lib.rs
src/pluto_eris/curve.rs
src/pluto_eris/engine.rs
src/pluto_eris/fields/fp.rs
src/pluto_eris/fields/fp12.rs
src/pluto_eris/fields/fp2.rs
src/pluto_eris/fields/fp6.rs
src/pluto_eris/fields/fq.rs
src/pluto_eris/fields/mod.rs
src/pluto_eris/mod.rs

Implementation of the half-pairing cycle of prime-order curves described here:  https://github.com/daira/pluto-eris
Pluto is a Barreto–Naehrig curve and its pairing implementation closely resembles that of `bn256` curve. See the Optimal Ate pairing described in the article: https://eprint.iacr.org/2010/354.pdf.
The constants for the fields and its extensions are derived these notebooks: https://github.com/davidnevadoc/ec-constants/tree/main/pluto_eris

Add Pluto-Eris cycle of curves

---

Cargo.toml
src/bn256/mod.rs
src/derive/field.rs

The functions `from_raw` and `from_u512` convert 256 and 512 bit values into their congruent field elements in Montgomery form.
In order to do this, the values are multiplied by the Montgomery constants `R2` and `R3` appropriately and then reduced.
Hosever, the values of `R2`  and `R3` may lie outside the acceptable bounds used in the asm optimized implementation. 
For this reason, we use an unrolled version of the multiplication and reduction algorithm when the `asm` feature is enabled.
This PR adds the aforementioned unrolled version for `from_u512` to fix the issue. It also adds the test that was used to find the bug.
Tested using:
`cargo nextest run --no-capture -E 'test(test_hash_to_curve_print)' --features "asm"`
Replaces (#103).
Closes (#100).

Fix asm version of `from_512`

---

Cargo.toml

Bumping up a new release for halo2curves.
CHANGELOG:
* Add field conversion to/from `[u64;4]` by @jonathanpwang in https://github.com/privacy-scaling-explorations/halo2curves/pull/80
* Compute Legendre symbol for `hash_to_curve` by @davidnevadoc in https://github.com/privacy-scaling-explorations/halo2curves/pull/77
* Add simplified SWU method by @davidnevadoc in https://github.com/privacy-scaling-explorations/halo2curves/pull/81
* Bring back curve algorithms for `a = 0` by @han0110 in https://github.com/privacy-scaling-explorations/halo2curves/pull/82
* fix: Improve serialization for prime fields by @huitseeker in https://github.com/privacy-scaling-explorations/halo2curves/pull/85
* refactor: (De)Serialization of points using `GroupEncoding` by @huitseeker in …

chore: Bump to 0.5.0 for release

---

src/secp256k1/curve.rs

Improve the `iso_map_secp256k1` func by avoiding the scalar inversions at all.
- use the jacobian coordinates instead of affine one in the func
- update the iso_map logic by using jacobian coordinates

improve: avoid the inversions in `iso_map_secp256k1`

---

Cargo.toml
README.md

* feat: implement the SSWU hash_to_curve for `secp256k1` by @duguorong009 in https://github.com/privacy-scaling-explorations/halo2curves/pull/110
* Add badges in README.md by @baumstern in https://github.com/privacy-scaling-explorations/halo2curves/pull/119
* change: Move from `maybe_rayon` to `rayon-1.8` by @CPerezz in https://github.com/privacy-scaling-explorations/halo2curves/pull/122
* chore:fix typos by @AdventureSeeker987 in https://github.com/privacy-scaling-explorations/halo2curves/pull/118
* Add FieldBits impl for Secp256r1 & remove `utils` module by @CPerezz in https://github.com/privacy-scaling-explorations/halo2curves/pull/123
* improve: avoid the inversions in `iso_map_secp256k1` by @duguorong009 in https://github.com/privacy-scaling-explorations/halo2curves/pull/124
* …

Bump lib to 0.6.0

---

Cargo.toml

This line https://github.com/privacy-scaling-explorations/halo2curves/blob/main/src/ff_ext/mod.rs#L18 actually requires `subtle 2.5`, so I think it makes sense to bump the version here to force users bump too. It happened to us that subtle 2.4.1 was elected and didn't have this feature. subtle 2.5 works.

upgrade subtle

---

src/msm.rs

Batch affine addition with scheduler approach as in [CycloneMSM](https://eprint.iacr.org/2022/1396.pdf) is implemented. This PR also should cover some part of the optimisation suggestions [in here](https://github.com/privacy-scaling-explorations/halo2/issues/187)
Batch addition looks like below for example for 16 additions.
```
b0' = b0 + p0
b1' = b1 + p1
...
b15' = b15 + p15
```
And in affine coordinates we use a shared inversion for all add operation so that batch [affine addition](https://github.com/ethereum/py_ecc/blob/d5e5b2086483f9047cdaabf97eba7021bdf27168/py_ecc/bn128/bn128_curve.py#L89) becomes cheaper than [jacobian addition](https://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-0.html). In scheduler technique we update multiple buckets at once. Natuurally same buckets in …

MSM optimisations: CycloneMSM

---

src/bn256/curve.rs

Subgroup membership check in G2 is group order exponentiation. This PR makes it much more cheaper replacing with method ported from gnark-crypto

Faster G2 subgroup check for BN curve

---

benches/hash_to_curve.rs
src/derive/curve.rs
src/ff_ext/mod.rs

src/derive/curve.rs: 
- Fixes a typo in a macro comment to correctly reference the `$name_affine` variable, ensuring consistency between the code and its description.
benches/hash_to_curve.rs: 
- Corrects a grammatical error (`basic the` -> `the basic`) in the file's documentation comment.
src/ff_ext/mod.rs: 
- Capitalizes `Legendre symbol` to follow the standard convention for proper nouns in technical documentation.

docs: Fix typos and grammatical errors in comments
